
services:
  toolbox:
    image: ci-cd.science.uu.nl/toolbox:v0.1.0
    ports:
      - "8080:8080"
    environment:
      HADDOCK3_INT_RESCORE_ENDPOINT: http://haddock3-rescore:9000

  haddock3-rescore:
    build:
      context: .
      dockerfile: Dockerfiles/haddock3-rescore.Dockerfile
    ports:
      - "9000:9000"